### ISSUE TITLE
Filesystem storage conversion

### ISSUE THREAD

**Issue by RaymondKirk** [RaymondKirk/topic_store#20]
Sometimes the pickled files on disk cannot be unpickled (wrong data format).

**Comment by nikostsagk** [comment]
It seems to work for conversions between `.topic_store` and `database` but converting to `.bag` returns the following error:

```
Traceback (most recent call last):
  File "/home/thorvald/rasberry_ws/src/topic_store/scripts/convert.py", line 14, in <module>
    _convert_cli()
  File "/home/thorvald/rasberry_ws/src/topic_store/src/topic_store/convert.py", line 164, in _convert_cli
    topic_store_to_ros_bag(input_path, output_path)
  File "/home/thorvald/rasberry_ws/src/topic_store/src/topic_store/convert.py", line 123, in topic_store_to_ros_bag
    msgs = item.to_ros_msg_list()
  File "/home/thorvald/rasberry_ws/src/topic_store/src/topic_store/data.py", line 145, in to_ros_msg_list
    return list(TopicStore.__ros_msg_dict_to_list(self.msgs))
  File "/home/thorvald/rasberry_ws/src/topic_store/src/topic_store/data.py", line 43, in msgs
    self.__msgs = rosify_dict(self.dict)
  File "/home/thorvald/rasberry_ws/src/topic_store/src/topic_store/sanitation.py", line 186, in __call__
    value = self._exit_fn(parents, key, old_object, new_object, new_items)
  File "/home/thorvald/rasberry_ws/src/topic_store/src/topic_store/sanitation.py", line 359, in exit_fn_dict_to_ros
    setattr(new_object, attribute_key, attribute_value)
AttributeError: 'Image' object has no attribute 'callerid'
```

**Comment by RaymondKirk** [comment]
I haven't seen that error in my tests Niko, could you send me the file you're trying to convert?
